### ISSUE TITLE
Could you add a SSE example that uses `Source.actorRef` ?

### ISSUE THREAD

**Issue by rtyley** [playframework/play-scala-streaming-example#11]
I'm experimenting with Server Sent Events, and while the existing `streamClock()` example is nice, I've failed in adapting it to my purpose. I'd like:

* a 'writable' `Source[String, _]` that I can push data into arbitrarily at a later date. Is that what `Source.actorRef()` is for?
* a `Publisher` for which `fanout` is true (ie `Sink.asPublisher(fanout = true)`), so that multiple clients can all receive the resulting server-sent events.

I hope those are reasonable things to want, and that server-sent events are a reasonable way to achieve it. You can imagine a site with a big red button, and another 'viewer' page which many people could view - when the button is pressed, all users should see that event relayed on the 'viewer' page, simultaneously.

Here's the kind of code I've been trying:

```
  val (actorRef, publisher) =
    Source.actorRef[String](1000, OverflowStrategy.dropHead).toMat(Sink.asPublisher(fanout = true))(Keep.both).run()

  val sourceFromPublisher = Source.fromPublisher(publisher).log("actorPublisher")

  def streamClock() = Action {
    Ok.chunked(sourceFromPublisher via EventSource.flow).as(ContentTypes.EVENT_STREAM)
  }
```
_(see https://github.com/rtyley/play-streaming-scala/commit/77572a8c69ff1181120af211897a0bf4958f99c2#diff-0558d2a6b4820ecb3797f61ab919efb4 for this code in a compiling branch)_

When I try this, I sometimes get success - everything works as intended, but more often than not, I get this error:

```
[error] a.s.Materializer - [actorPublisher] Upstream failed.
akka.stream.impl.ActorPublisher$NormalShutdownException: Cannot subscribe to shut-down Publisher
```

...the intermittent nature of the error suggests to me that there's some kind of race-condition going on, with the publisher often getting shut-down before it can be registered for use. What's the proper way to use this stuff?!

https://www.playframework.com/documentation/2.5.x/ScalaComet

cc @wsargent

**Comment by rtyley** [comment]
cc @jmhofer !

**Comment by wsargent** [comment]
@rtyley You can adapt https://github.com/playframework/play-chatroom-scala to make use of the Dynamic Streams functionality -- http://doc.akka.io/docs/akka/current/scala/stream/stream-dynamic.html

This API didn't exist at the time of writing, which is why the example here has to use a publisher / actor interface.

**Comment by wsargent** [comment]
@rtyley bonus points if you can submit it back as a PR!

**Comment by rtyley** [comment]
Many thanks for your reply - so are you suggesting that I use a `MergeHub` and `BroadcastHub`, feeding in `Source.single("things").runWith(toConsumer)` as in http://doc.akka.io/docs/akka/current/scala/stream/stream-dynamic.html#Using_the_MergeHub ?

Just to give more detail about my specific use-case, I want to consume data from a kinesis stream - which basically means polling it - and dump any new events into the flow, which should go to all clients by SSE. If any client can not receive an event, it should have a small buffer, but should not block the flow for other clients.

**Comment by rtyley** [comment]
I've got it working with https://github.com/rtyley/play-streaming-scala/commit/44fee4b294504deb7e2e59a8079cededa51f3582 - not quite PR ready, as it stomps over the previous code, but it seems to work, thank you!  I'm still a little confused about which way round the roles of `MergeHub` and `BroadcastHub` are - looks like the `BroadcastHub` provides the sink that I post the ad-hoc messages into...?!

**Comment by wsargent** [comment]
Awesome!  I recommend Johan's blog post as well for getting a handle on hub stuff: https://markatta.com/codemonkey/blog/2016/10/02/chat-with-akka-http-websockets/

**Comment by wsargent** [comment]
@rtyley any word on this?  Play 2.6.x will be coming out soon and I'd like to have this functionality as part of it.

**Comment by rtyley** [comment]
> Play 2.6.x will be coming out soon and I'd like to have this functionality as part of it.

You're interested in me contributing a SSE example that uses `Source.actorRef`? I can try to get to that?

**Comment by wsargent** [comment]
So you can see https://github.com/playframework/play-scala-websocket-example/blob/2.6.x/app/actors/UserActor.scala#L36 has a broadcast hub / merge hub solution now.

**Comment by wsargent** [comment]
See also https://github.com/playframework/playframework/issues/6246

**Comment by wsargent** [comment]
Closing (there are solutions in other examples available)
